# wrangler.toml
name = 'play-scraper-api'
main = "_worker.js"
compatibility_date = "2024-02-20"
keep_vars = true

# KV 存储（保存应用配置和通知状态）
[[kv_namespaces]]
binding = "KV"
id = "8b89d8b5c511457390f5aee4cce00570"

# 添加定时触发器：每小时的第 0 分钟执行一次（UTC时间）
[triggers]
crons = ["0 * * * *"]

# 静态资源配置 - 托管前端 HTML
[assets]
directory = "public"
binding = "ASSETS"
